[package]
name = "sui_elipse"
version = "0.1.0"
edition = "2018"
license = "AGPL-3.0"



[dependencies]
url = "2.2.2"
anyhow = "1.0.5"
rand = "0.8.5"
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]